# Generated by Django 4.0.2 on 2022-02-22 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jogo', models.IntegerField(blank=True, null=True, verbose_name='Numero Jogo')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('ganhador', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Ganhador')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='NumeroSorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField(blank=True, null=True, verbose_name='1')),
                ('n2', models.IntegerField(blank=True, null=True, verbose_name='2')),
                ('n3', models.IntegerField(blank=True, null=True, verbose_name='3')),
                ('n4', models.IntegerField(blank=True, null=True, verbose_name='4')),
                ('n5', models.IntegerField(blank=True, null=True, verbose_name='5')),
                ('n6', models.IntegerField(blank=True, null=True, verbose_name='6')),
                ('n7', models.IntegerField(blank=True, null=True, verbose_name='7')),
                ('n8', models.IntegerField(blank=True, null=True, verbose_name='8')),
                ('n9', models.IntegerField(blank=True, null=True, verbose_name='9')),
                ('n10', models.IntegerField(blank=True, null=True, verbose_name='10')),
                ('n11', models.IntegerField(blank=True, null=True, verbose_name='11')),
                ('n12', models.IntegerField(blank=True, null=True, verbose_name='12')),
                ('n13', models.IntegerField(blank=True, null=True, verbose_name='13')),
                ('n14', models.IntegerField(blank=True, null=True, verbose_name='14')),
                ('n15', models.IntegerField(blank=True, null=True, verbose_name='15')),
                ('n16', models.IntegerField(blank=True, null=True, verbose_name='16')),
                ('n17', models.IntegerField(blank=True, null=True, verbose_name='17')),
                ('n18', models.IntegerField(blank=True, null=True, verbose_name='18')),
                ('n19', models.IntegerField(blank=True, null=True, verbose_name='19')),
                ('n20', models.IntegerField(blank=True, null=True, verbose_name='20')),
                ('id_jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jogo', verbose_name='Numero Jogo')),
            ],
            options={
                'verbose_name': 'Numero Sorteado',
                'verbose_name_plural': 'Numeros Sorteados',
            },
        ),
        migrations.CreateModel(
            name='NumeroRepetido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1', models.IntegerField(blank=True, null=True, verbose_name='1')),
                ('n2', models.IntegerField(blank=True, null=True, verbose_name='2')),
                ('n3', models.IntegerField(blank=True, null=True, verbose_name='3')),
                ('n4', models.IntegerField(blank=True, null=True, verbose_name='4')),
                ('n5', models.IntegerField(blank=True, null=True, verbose_name='5')),
                ('n6', models.IntegerField(blank=True, null=True, verbose_name='6')),
                ('n7', models.IntegerField(blank=True, null=True, verbose_name='7')),
                ('n8', models.IntegerField(blank=True, null=True, verbose_name='8')),
                ('n9', models.IntegerField(blank=True, null=True, verbose_name='9')),
                ('n10', models.IntegerField(blank=True, null=True, verbose_name='10')),
                ('id_jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jogo', verbose_name='Numero Jogo')),
            ],
            options={
                'verbose_name': 'Numero Repetido',
                'verbose_name_plural': 'Numeros Repetidos',
            },
        ),
    ]
